---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootkubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: labelforpods
  template:
    metadata:
      labels:
        app: labelforpods
    spec:
      containers:
        - name: springbootapptotestcicd
          image: us-central1-docker.pkg.dev/gmemoridev2016/cicd-cloud-build/heahealthcheckimage:new
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springbootcicdpipeline-service
spec:
  type: LoadBalancer
  selector:
    app: labelforpods
  ports:
    - port: 80
      targetPort: 8080

---